export const dataFromApi = {
  personnel: [
    {
      id: 1,
      fullname: "ماهر العرفاوي",
      grade_cat: "ضابط صف",
      garde: "وكيل",
      type_fonction: "إداري",
      type_age: "أ",
      age: "47",
      base: "القاعدة الجوية بالعوينة",
      unite: "الوحدة الجوية 11",
      bmi_moyen: 23,
      test_moyen: 11,
      qualification: true,
      exemption: true,
      exemption_finale: true,
    },

    {
      id: 1,
      fullname: "جمال قروي",
      grade_cat: "ضابط صف",
      garde: "عريف",
      type_fonction: "عملياتي",
      type_age: "أ",
      age: "45",
      base: "القاعدة الجوية بالخروبة",
      unite: "الوحدة الجوية 11",
      bmi_moyen: 25,
      test_moyen: 11,
      qualification: true,
      exemption: true,
      exemption_finale: true,
    },

    {
      id: 1,
      fullname: "ماهر العرفاوي",
      grade_cat: "ضابط صف",
      garde: "وكيل",
      type_fonction: "إداري",
      type_age: "أ",
      age: "47",
      base: "القاعدة الجوية برمادة",
      unite: "الوحدة الجوية 11",
      bmi_moyen: 21,
      test_moyen: 11,
      qualification: true,
      exemption: true,
      exemption_finale: true,
    },

    {
      id: 1,
      fullname: "أحمد بن عطية",
      grade_cat: "ضباط",
      garde: "عريف",
      type_fonction: "عملياتي",
      type_age: "ص",
      age: "45",
      base: "القاعدة الجوية بجبل الكبير",
      unite: "الوحدة الجوية 11",
      bmi_moyen: 20,
      test_moyen: 11,
      qualification: true,
      exemption: true,
      exemption_finale: true,
    },
    {
      id: 1,
      fullname: "أحمد بن عطية",
      grade_cat: "رجال جيش",
      garde: "عريف",
      type_fonction: "عملياتي",
      type_age: "ص",

      age: "45",
      base: "القاعدة الجوية سيدي أحمد",
      unite: "الوحدة الجوية 11",
      bmi_moyen: 23.5,
      test_moyen: 11,
      qualification: true,
      exemption: true,
      exemption_finale: true,
    },
    {
      id: 1,
      fullname: "أحمد بن عطية",
      grade_cat: "رجال جيش",
      garde: "عريف",
      type_fonction: "عملياتي",
      type_age: "ه",
      age: "45",
      base: "القاعدة الجوية صفاقس",
      unite: "الوحدة الجوية 11",
      bmi_moyen: 27,
      test_moyen: 11,
      qualification: true,
      exemption: true,
      exemption_finale: true,
    },
    {
      id: 1,
      fullname: "أحمد بن عطية",
      grade_cat: "رجال جيش",
      garde: "عريف",
      type_fonction: "عملياتي",
      type_age: "ه",
      age: "45",
      base: "القاعدة الجوية قابس",
      unite: "الوحدة الجوية 11",
      bmi_moyen: 27,
      test_moyen: 11,
      qualification: true,
      exemption: true,
      exemption_finale: true,
    },
    {
      id: 1,
      fullname: "أحمد بن عطية",
      grade_cat: "رجال جيش",
      garde: "عريف",
      type_fonction: "عملياتي",
      type_age: "ه",
      age: "45",
      base: "القاعدة الجوية قفصة",
      unite: "الوحدة الجوية 11",
      bmi_moyen: 26,
      test_moyen: 11,
      qualification: true,
      exemption: true,
      exemption_finale: true,
    },
    {
      id: 1,
      fullname: "أحمد بن عطية",
      grade_cat: "رجال جيش",
      garde: "عريف",
      type_fonction: "عملياتي",
      type_age: "ص",

      age: "45",
      base: "القاعدة الجوية ببرج العامري",
      unite: "الوحدة الجوية 11",
      bmi_moyen: 18,
      test_moyen: 11,
      qualification: true,
      exemption: true,
      exemption_finale: true,
    },
    // *********************
    {
      id: 1,
      fullname: "ماهر العرفاوي",
      grade_cat: "ضابط صف",
      garde: "وكيل",
      type_fonction: "إداري",
      type_age: "د",
      age: "47",
      base: "القاعدة الجوية بالعوينة",
      unite: "الوحدة الجوية 12",
      bmi_moyen: 16,
      test_moyen: 11,
      qualification: true,
      exemption: true,
      exemption_finale: true,
    },

    {
      id: 1,
      fullname: "جمال قروي",
      grade_cat: "رجال جيش",
      garde: "عريف",
      type_fonction: "عملياتي",
      type_age: "د",
      age: "45",
      base: "القاعدة الجوية بالخروبة",
      unite: "الوحدة الجوية 12",
      bmi_moyen: 26,
      test_moyen: 11,
      qualification: true,
      exemption: true,
      exemption_finale: true,
    },

    {
      id: 1,
      fullname: "ماهر العرفاوي",
      grade_cat: "ضابط صف",
      garde: "وكيل",
      type_fonction: "إداري",
      type_age: "د",
      age: "47",
      base: "القاعدة الجوية برمادة",
      unite: "الوحدة الجوية 12",
      bmi_moyen: 20,
      test_moyen: 11,
      qualification: true,
      exemption: true,
      exemption_finale: true,
    },

    {
      id: 1,
      fullname: "أحمد بن عطية",
      grade_cat: "ضباط",
      garde: "عريف",
      type_fonction: "عملياتي",
      type_age: "ب",
      age: "45",
      base: "القاعدة الجوية بجبل الكبير",
      unite: "الوحدة الجوية 11",
      bmi_moyen: 20,
      test_moyen: 11,
      qualification: true,
      exemption: true,
      exemption_finale: true,
    },
    {
      id: 1,
      fullname: "أحمد بن عطية",
      grade_cat: "ضباط",
      garde: "عريف",
      type_fonction: "عملياتي",
      type_age: "ص",
      age: "45",
      base: "القاعدة الجوية سيدي أحمد",
      unite: "الوحدة الجوية 11",
      bmi_moyen: 24,
      test_moyen: 11,
      qualification: true,
      exemption: true,
      exemption_finale: true,
    },
    {
      id: 1,
      fullname: "أحمد بن عطية",
      grade_cat: "رجال جيش",
      garde: "عريف",
      type_fonction: "عملياتي",
      type_age: "ص",
      age: "45",
      base: "القاعدة الجوية صفاقس",
      unite: "الوحدة الجوية 11",
      bmi_moyen: 28,
      test_moyen: 11,
      qualification: true,
      exemption: true,
      exemption_finale: true,
    },
    {
      id: 1,
      fullname: "أحمد بن عطية",
      grade_cat: "رجال جيش",
      garde: "عريف",
      type_fonction: "عملياتي",
      type_age: "ص",
      age: "45",
      base: "القاعدة الجوية قابس",
      unite: "الوحدة الجوية 11",
      bmi_moyen: 19,
      test_moyen: 11,
      qualification: true,
      exemption: true,
      exemption_finale: true,
    },
    {
      id: 1,
      fullname: "أحمد بن عطية",
      grade_cat: "ضباط",
      garde: "عريف",
      type_fonction: "عملياتي",
      type_age: "أ",
      age: "45",
      base: "القاعدة الجوية قفصة",
      unite: "الوحدة الجوية 12",
      bmi_moyen: 18,
      test_moyen: 11,
      qualification: true,
      exemption: true,
      exemption_finale: true,
    },
    {
      id: 1,
      fullname: "أحمد بن عطية",
      grade_cat: "ضباط",
      garde: "عريف",
      type_fonction: "عملياتي",
      type_age: "أ",
      age: "45",
      base: "القاعدة الجوية ببرج العامري",
      unite: "الوحدة الجوية 11",
      bmi_moyen: 15,
      test_moyen: 11,
      qualification: true,
      exemption: true,
      exemption_finale: true,
    },
    {
      id: 1,
      fullname: "ماهر العرفاوي",
      grade_cat: "ضابط صف",
      garde: "وكيل",
      type_fonction: "إداري",
      type_age: "أ",
      age: "47",
      base: "القاعدة الجوية بالعوينة",
      unite: "الوحدة الجوية 11",
      bmi_moyen: 15,
      test_moyen: 11,
      qualification: true,
      exemption: true,
      exemption_finale: true,
    },
    {
      id: 1,
      fullname: "ماهر العرفاوي",
      grade_cat: "ضابط صف",
      garde: "وكيل",
      type_fonction: "إداري",
      type_age: "د",
      age: "47",
      base: "القاعدة الجوية بالعوينة",
      unite: "الوحدة الجوية 11",
      bmi_moyen: 17,
      test_moyen: 11,
      qualification: true,
      exemption: true,
      exemption_finale: true,
    },
    {
      id: 1,
      fullname: "ماهر العرفاوي",
      grade_cat: "ضابط",
      garde: "وكيل",
      type_fonction: "إداري",
      type_age: "د",
      age: "47",
      base: "القاعدة الجوية بالعوينة",
      unite: "الوحدة الجوية 12",
      bmi_moyen: 17,
      test_moyen: 11,
      qualification: true,
      exemption: true,
      exemption_finale: true,
    },
    {
      id: 1,
      fullname: "ماهر العرفاوي",
      grade_cat: "ضابط",
      garde: "وكيل",
      type_fonction: "إداري",
      type_age: "ب",
      age: "47",
      base: "القاعدة الجوية بالعوينة",
      unite: "الوحدة الجوية 12",
      bmi_moyen: 20,
      test_moyen: 11,
      qualification: true,
      exemption: true,
      exemption_finale: true,
    },
    {
      id: 1,
      fullname: "ماهر العرفاوي",
      grade_cat: "رجال جيش",
      garde: "وكيل",
      type_fonction: "إداري",
      type_age: "ص",
      age: "47",
      base: "القاعدة الجوية بالعوينة",
      unite: "الوحدة الجوية 51",
      bmi_moyen: 22,
      test_moyen: 11,
      qualification: true,
      exemption: true,
      exemption_finale: true,
    },
    {
      id: 1,
      fullname: "ماهر العرفاوي",
      grade_cat: "رجال جيش",
      garde: "وكيل",
      type_fonction: "إداري",
      type_age: "ص",
      age: "47",
      base: "القاعدة الجوية بالخروبة",
      unite: "الوحدة الجوية 51",
      bmi_moyen: 21,
      test_moyen: 11,
      qualification: true,
      exemption: true,
      exemption_finale: true,
    },

    {
      id: 1,
      fullname: "ماهر العرفاوي",
      grade_cat: "ضابط صف",
      garde: "وكيل",
      type_fonction: "إداري",
      type_age: "د",
      age: "47",
      base: "القاعدة الجوية بالخروبة",
      unite: "الوحدة الجوية 11",
      bmi_moyen: 24,
      test_moyen: 11,
      qualification: true,
      exemption: true,
      exemption_finale: true,
    },
    {
      id: 1,
      fullname: "ماهر العرفاوي",
      grade_cat: "ضابط",
      garde: "وكيل",
      type_fonction: "إداري",
      type_age: "د",
      age: "47",
      base: "القاعدة الجوية بالخروبة",
      unite: "الوحدة الجوية 12",
      bmi_moyen: 24,
      test_moyen: 11,
      qualification: true,
      exemption: true,
      exemption_finale: true,
    },
    {
      id: 1,
      fullname: "ماهر العرفاوي",
      grade_cat: "ضابط",
      garde: "وكيل",
      type_fonction: "إداري",
      type_age: "ب",
      age: "47",
      base: "القاعدة الجوية بالخروبة",
      unite: "الوحدة الجوية 12",
      bmi_moyen: 24,
      test_moyen: 11,
      qualification: true,
      exemption: true,
      exemption_finale: true,
    },
    {
      id: 1,
      fullname: "ماهر العرفاوي",
      grade_cat: "رجال جيش",
      garde: "وكيل",
      type_fonction: "إداري",
      type_age: "أ",
      age: "47",
      base: "القاعدة الجوية بالخروبة",
      unite: "الوحدة الجوية 51",
      bmi_moyen: 23,
      test_moyen: 11,
      qualification: true,
      exemption: true,
      exemption_finale: true,
    },
    {
      id: 1,
      fullname: "ماهر العرفاوي",
      grade_cat: "رجال جيش",
      garde: "وكيل",
      type_fonction: "إداري",
      type_age: "ب",
      age: "47",
      base: "القاعدة الجوية بالخروبة",
      unite: "الوحدة الجوية 51",
      bmi_moyen: 26,
      test_moyen: 11,
      qualification: true,
      exemption: true,
      exemption_finale: true,
    },
  ],
};

//  sport_qualification: [
//         {
//           year: "2022",
//           quarter: "1",
//         },
//         {
//           year: "2022",
//           quarter: "2",
//         },
//         {
//           year: "2021",
//           quarter: "1",
//         },
//         {
//           year: "2021",
//           quarter: "2",
//         },
//         {
//           year: "2020",
//           quarter: "1",
//         },
//         {
//           year: "2020",
//           quarter: "2",
//         },
//       ],
//       mesure: [
//         {
//           year: "2022",
//           quarter: "1",
//           taille: 1.7,
//           poids: 68,
//         },
//         {
//           year: "2022",
//           quarter: "2",
//           taille: 1.7,
//           poids: 70,
//         },
//         {
//           year: "2021",
//           quarter: "1",
//           taille: 1.7,
//           poids: 75,
//         },
//         {
//           year: "2021",
//           quarter: "2",
//           taille: 1.7,
//           poids: 79,
//         },
//         {
//           year: "2020",
//           quarter: "1",
//           taille: 1.7,
//           poids: 82,
//         },
//         {
//           year: "2020",
//           quarter: "2",
//           taille: 1.7,
//           poids: 80,
//         },
//       ],
//       test: [
//         {
//           year: "2022",
//           quarter: "1",
//           note_updos: 12.5,
//           note_pompe: 10,
//           double_maille: 11,
//         },
//         {
//           year: "2022",
//           quarter: "2",
//           note_updos: 12.5,
//           note_pompe: 10,
//           double_maille: 11,
//         },
//         {
//           year: "2021",
//           quarter: "1",
//           note_updos: 12.5,
//           note_pompe: 10,
//           double_maille: 11,
//         },
//         {
//           year: "2021",
//           quarter: "2",
//           note_updos: 12.5,
//           note_pompe: 10,
//           double_maille: 11,
//         },
//         {
//           year: "2020",
//           quarter: "1",
//           note_updos: 12.5,
//           note_pompe: 10,
//           double_maille: 11,
//         },
//         {
//           year: "2020",
//           quarter: "2",
//           note_updos: 12.5,
//           note_pompe: 10,
//           double_maille: 11,
//         },
//       ],
//       bmi: [
//         {
//           year: "2022",
//           quarter: "1",
//           value: 20,
//         },
//         {
//           year: "2022",
//           quarter: "2",
//           value: 21,
//         },
//         {
//           year: "2021",
//           quarter: "1",
//           value: 22,
//         },
//         {
//           year: "2021",
//           quarter: "2",
//           value: 23,
//         },
//         {
//           year: "2020",
//           quarter: "1",
//           value: 22,
//         },
//         {
//           year: "2020",
//           quarter: "2",
//           value: 20,
//         },
//       ],
